### ISSUE TITLE
google-sheets actor task is not populating data from actor task

### ISSUE THREAD

**Issue by cptcrunchy** [metalwarrior665/actor-google-sheets#1]
I have not been able to successfully export data after the actor runs its task. I have followed the docs and added a **Finish webhook URL** and a **Finish webhook data** with the ID of my google sheet. The google sheet has not had any new data populated after converting from a crawler to an actor task. Is there something I am doing incorrect?

**Comment by metalwarrior665** [comment]
Sorry for not replying earlier here. The new version of the actor has documentation how to use new Apify Webhooks properly.
