### ISSUE TITLE
Integration with  Apify Cheerio

### ISSUE THREAD

**Issue by abhyuday123** [metalwarrior665/actor-google-sheets#29]
Need assistance in integrating the google sheet export feature with a cheerio task. I can independently copy-paste the dataset ID and then run the google sheet export tool but how to integrate the tool so the data gets pushed after every run of the cheerio scraper.

**Comment by metalwarrior665** [comment]
Hello,

I'm sorry that I did not see your reply before.

You just need to put a webhook into the cheerio scraper actor/task. The webhook should be a run endpoint of this Google-sheets actor. It will then automatically pick up the dataset. 

All is explained in the readme - https://github.com/metalwarrior665/actor-google-sheets#Webhooks
